import type { Metadata } from "next";
import "./globals.css";
import Header from "@/Components/modules/Header/Header";
import Footer from "@/Components/modules/Footer/Footer";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" dir="rtl">
      <body className="bg-gray-900">
        <Header />
        <Toaster />
        {children}
        <Footer />
      </body>
    </html>
  );
}
